#!/bin/sh

SUCCESS="printf \033[1;32m"
FAILURE="printf \033[1;31m"
WARNING="printf \033[1;33m"
MESSAGE="printf \033[1;34m"
NORMAL="printf \033[0;39m"

echo Check commands...

CMDS="wget unzip cabextract objdump"

for x in $CMDS; do
  echo -n "Check $x... "
  which $x || ($FAILURE;echo " No $x utility found! Please install first";$NORMAL; exit 1)
done

wget -N https://github.com/upx/upx/releases/download/v4.0.0/upx-4.0.0-amd64_linux.tar.xz

upxtgz=$(ls -t upx*.xz)
echo Untar UPX $upxtgz
mkdir upx
tar xvf $upxtgz --strip-components=1 -C upx

wget -N https://home.apache.org/~steffenal/VC15/binaries/httpd-2.4.54-win64-VC15.zip
#wget -N https://windows.php.net/downloads/releases/archives/php-7.2.34-Win32-VC15-x64.zip
wget -N https://windows.php.net/downloads/releases/archives/php-7.4.32-Win32-vc15-x64.zip
#wget -N http://nginx.org/download/nginx-1.23.2.zip

# rcs57 for win32
#wget -N https://www.cs.purdue.edu/homes/trinkle/RCShome/rcs57pc1.zip
wget -N https://github.com/wkpark/rcs57pc/releases/download/v5.7/rcs-5.7-18744e3f9.zip
# diffutils-2.7.1 for win32
wget -N https://github.com/wkpark/pc-diffutils/releases/download/v2.7.1-pc/diffutils-2.7.1-ccf4bd084.zip

# vc_redist.x64
wget -N https://aka.ms/vs/17/release/vc_redist.x64.exe

# graphviz
#wget -N https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/6.0.2/windows_10_cmake_Release_graphviz-install-6.0.2-win64.exe

## extract
## newest first
httpdzip=$(ls -t httpd-*zip | head -1)
echo Unzip Apache $httpdzip ...
unzip -u $httpdzip -d apache

phpzip=$(ls -t php-*zip | head -1)
echo Unzip PHP $phpzip ...
unzip -u $phpzip -d php7

#echo Unzip rcs57pc1
#unzip rcs57pc1.zip -d rcs57pc1

rcszip=$(ls -t rcs-*zip | head -1)
echo Unzip RCS $rcszip ...
unzip -u $rcszip -d rcs57pc

diffzip=$(ls -t diffutils-*zip | head -1)
echo Unzip diffutils $diffzip ...
unzip -u $diffzip -d diffutils

vcexe=$(ls -t vc_redist*.exe | head -1)
echo Cabextract vc_redist $vcexe ...
cabextract $vcexe -d vc
(cd vc; cabextract *)

#echo Nginx
#unzip nginx-1.23.2.zip

exit 0
