#!/bin/sh
#### apache

cat <<EOF | sed 's,^,modules/,;s,$,.so,' > apache-modules
mod_alias
mod_access_compat
mod_authz_core
mod_dir
mod_env
mod_log_config
mod_mime
mod_rewrite
mod_setenvif
mod_file_cache
mod_authz_host
mod_autoindex
mod_cgi
mod_deflate
EOF

mkdir -p Apache24/logs
mkdir -p Apache24/bin
(cd apache/Apache24; tar cvf - *.txt cgi-bin bin/iconv conf icons htdocs -T ../../apache-modules ) | (cd Apache24;tar xf -)
cp apache/ReadMe.txt apache/ReadMe-VC15.txt

# save original conf
if [ ! -f Apache24/conf/httpd.conf.orig ]; then
cp Apache24/conf/httpd.conf Apache24/conf/httpd.conf.orig
fi

# fix some configs
sed 's,^Define SRVROOT.*,Define SRVROOT ".",' Apache24/conf/httpd.conf.orig > tmp.conf
sed 's,^Listen 80,Listen 8800,' tmp.conf > tmp2.conf

sed 's,^#Include conf/extra/httpd-default.conf,Include conf/extra/httpd-default.conf,' tmp2.conf > tmp.conf
sed 's,^#Include conf/extra/httpd-autoindex.conf,Include conf/extra/httpd-autoindex.conf,' tmp.conf > tmp2.conf

# change documentRoot
sed 's,^DocumentRoot "\${SRVROOT}/htdocs,DocumentRoot "../moniwiki,' tmp2.conf > tmp.conf
sed 's,^<Directory "\${SRVROOT}/htdocs,<Directory "../moniwiki,' tmp.conf > tmp2.conf

# change servername
sed '/^#ServerName /c ServerName localhost.localdomain' tmp2.conf > tmp.conf

# add conf.d
echo "Include conf.d/*.conf" >> tmp.conf

####
#cp tmp2.conf tmp.conf

mkdir -p Apache24/conf.d

cat Apache24/conf/httpd.conf.orig | grep '^LoadModule \|^#LoadModule ' >all.modules.orig

cat all.modules.orig |awk '{print "#LoadModule",$2,$3}' > all.modules
RE=$(cat apache-modules |cut -c13- | sed 's,.so$,,' | tr '\n' '|')
cat all.modules | sed -E "s,#LoadModule(.*mod_($RE)\.so.*)$,LoadModule\\1," > new.modules

# find line number
N=$(sed -n '/LoadModule access_compat_module/=' Apache24/conf/httpd.conf.orig)
N=$(expr $N - 1)
# remove module lines
sed -n '/LoadModule access_compat_module/,/xml2enc_module/!p' tmp.conf > tmp2.conf
# replace new module lines
sed "${N}r new.modules" tmp2.conf > Apache24/conf/httpd.conf

#rm tmp.conf tmp2.conf

cat <<'EOF' | sed 's,$,,' > Apache24/conf.d/httpd-php.conf
LoadModule php7_module "..\php\php7apache2_4.dll"
# configure the path to php.ini
PHPIniDir "..\php"

AddType application/x-httpd-php .php
EOF

cat <<'EOF' | sed 's,$,,' > Apache24/conf.d/default.conf
AddDefaultCharset utf-8

<Location ~ "^/(config|tools|lib|data)">
    Order allow,deny
    Deny from all
</Location>

<Location ~ "^/(pds|_cache)">
    AddType text/plain .php .php3 .php4 .php5 .sh .cgi .pl .py .phtml .html
    php_value engine off
    Options -Indexes
</Location>

<Location "/">
    Options -Indexes
    #Options None
    #AllowOverride All
</Location>
EOF

DISTS="ab.exe
ApacheMonitor.exe
htcacheclean.exe
htdbm.exe
htdigest.exe
htpasswd.exe
httpd.exe
libapr-1.dll
libapriconv-1.dll
libaprutil-1.dll
libhttpd.dll
pcre2-8.dll
pcre.dll
rotatelogs.exe
wintty.exe
zlib1.dll"

(cd Apache24; for x in $DISTS; do cp -a ../apache/Apache24/bin/$x bin/;done; ../upx/upx bin/*.dll bin/*.exe bin/iconv/*.so)

cat <<'EOF' | sed 's,$,,' > Apache24/start.cmd
@echo off
ECHO Loading Apache ...
REM add the PHP path to load extensions
SET PATH=%~dp0\bin;%~dp0\..\php;%PATH%
ECHO Press CTRL+C or use a process-killer to stop the apache

start /min httpd.exe -w
REM pause
EOF

cat <<'EOF' | sed 's,$,,' > Apache24/stop.cmd
@echo off
ECHO Shutdown Apache ...
SET PATH=%~dp0\bin;%~dp0\..\php;%PATH%

taskkill /f /im httpd.exe
pause
EOF

cat <<'EOF' | sed 's,$,,' > start.cmd
@echo off
cd Apache24
call start.cmd
EOF

cat <<EOF > home.url
[InternetShortcut]
URL=http://localhost:8800/wiki.php/FrontPage
EOF

exit 0
